# Configuration for Code Analysis models
code_analysis_model: "microsoft/codebert-base" # This remains the base model for general embeddings

# Configuration for fine-tuned vulnerability detection model from GitHub Release
github_repo_owner: "sailaja-AI"
github_repo_name: "AgenticAI"
github_release_tag: "v1.0.0" # The specific tag of your release
github_release_asset_name: "final_model.zip" # The exact filename of the zipped model in the release
local_model_cache_dir: "AgentAI_Data/trained_models/final_model_from_release" # Where to save/extract locally

