name: AI Security Scan

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download Trained Models from GitHub Release
      run: |
        # The gh CLI is pre-installed on GitHub runners
        # Download the RL agent model
        gh release download v1.0.0 --pattern 'rl_model.zip' --clobber

        # Download the fine-tuned CodeBERT model and unzip it
        gh release download v1.0.0 --pattern 'final_model.zip' --clobber
        unzip -o final_model.zip -d results_codebert/
      env:
        # The GITHUB_TOKEN is automatically provided by GitHub Actions
        # It gives the workflow permission to download from releases in the same repository.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run AI Vulnerability Scan
      run: |
        echo "--- Verifying downloaded files for debugging ---"
        ls -lR
        echo "-----------------------------------------------"
        
        python -m src vulnerable_app.py

